---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: azure_configure
    inherits: 
    description: 
  fields:
  - configurechilddialog:
      value: azure_configure
